### ISSUE TITLE
Input support for Tensorflow.data.Dataset

### ISSUE THREAD

**Issue by GalAvineri** [netrack/keras-metrics#17]
Hello! :)
Firstly I would like to thank you for this greatly useful repository!

Secondly I would like to ask:
Do the metrics functions you provide support an input of Tensorflow.data.Dataset, like the normal metrics of keras does?

**Comment by GalAvineri** [comment]
At first I had issues using tf.data.Dataset as input, but now it totally works, so it seems to be a problem at my side, thank you!

**Comment by ybubnov** [comment]
@GalAvineri, no problem, thank you!
