### ISSUE TITLE
What about multi-class classifiers?

### ISSUE THREAD

**Issue by gopchandani** [netrack/keras-metrics#2]
Was just going through the code, not sure if I understand this correctly. 

Are these metrics only good for binary classifiers? How does one interpret the output for precision/recall if a multi-class classifier is being trained?

**Comment by ybubnov** [comment]
@gopchandani, Hi, thank you for the question.

> Are these metrics only good for binary classifiers?

These metrics works for multiclass classifiers as well, you simply need to binarize the output vector:
```py
import keras
import keras_metrics

num_classes = 10

model = models.Sequential()
model.add(keras.layers.Dense(512, activation="relu", input_dim=128))
model.add(keras.layers.Dense(128, activation="relu"))
model.add(keras.layers.Dense(num_classes, activation="softmax"))

model.compile(optimizer="nadam",
              loss="categorical_crossentropy",
              metrics=[keras_metrics.precision(), keras_metrics.recall()])

# Train the model. Content of the x_batch variable looks an
# array of attribute vectors. Content of the y_batch looks like
# an array of labels, where label is a value in a range [0, num_classes)
#
#  x_batch = [ [0.4, 0.2, ..., 0.1],
#              [0.1, 0.3, ..., 0.2] ]
#
#  y_batch = [2, 1, ..., 9]
#
x_batch, y_batch = read_next()
y_batch = keras.utils.to_categorical(y_batch, num_classes)

model.train_on_batch(x_batch, y_batch)

# Retrieve the testing data from some source.
x_true, y_true = read_next()

# Binarize the output.
y_true = keras.utils.to_categorical(y_true, num_classes)

# Evaluate the metrics.
loss_and_metrics = model.evaluate(x_true, y_true)
```

> How does one interpret the output for precision/recall if a multi-class classifier is being trained?

I'm not sure if understood you question correctly. The precision/recall will be calculated on the evaluation step only, training does not trigger the metrics calculation. Metrics are calculated across all classes of a model and not on per-class basis.

Do you want me to add this code snippet to the documentation as an example or do something else to improve the package understanding?

**Comment by Avcu** [comment]
hi @gopchandani, these metrics are defined for the binary classification problem specifically in the first place. Is there something similar metric you want to observe for multi-classification problem? Can you be more specific?

**Comment by nmatare** [comment]
@ybubnov , the above example does not work. It throws the error:

`'ValueError: With 2 and more output classes a metric label must be specified'`

It's unclear where you specify the labels for multiclass, as using the 'labels' parameter doesn't resolve the exception.

**Comment by Avcu** [comment]
@nmatare hi, the code above is not a correct way of implementing this library.  Please kindly refer to read me file https://github.com/netrack/keras-metrics/blob/master/README.md . If you dont understand why it is not feasible to do something like that refer to following link https://github.com/netrack/keras-metrics/pull/8 .

**Comment by ybubnov** [comment]
Closing, as there is no more activity in this thread.
