### ISSUE TITLE
 TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by DomenicoMessina** [netrack/keras-metrics#51]
I tried to customize keras-metrics, because i want to use a balanced_accuracy as metric. So i added keras-metrics in a folder of my project, but i can't modify ìt as well.  
In metrics.py:
` 
def __init__(self, name=None, label=0, cast_strategy=None, **kwargs):
        super(layer, self).__init__(name=name, **kwargs)
        self.stateful = True
        self.label = label
        self.cast_strategy = cast_strategy
        self.epsilon = K.constant(K.epsilon(), dtype="float64")
`

but  cast_strategy is called, there is
`return self.cast_strategy(
            y_true, y_pred, dtype=dtype, label=self.label)
`
cast strategy is not callable! Can someone help me? I'm working for my master thesis.

**Comment by ybubnov** [comment]
Hi @DomenicoMessina, you should pass one of the cast strategies in order to make things work. For example, with `true_positive` metric:
```py
from keras_metrics import metrics
from keras_metrics import casts

binary_true_positive = metrics.true_positive(name="tp", cast_strategy=casts.binary)
```
